---
title: "SoCal Data Science Program"
subtitle: "Summer 2024 Schedule"
format: 
  html:
    toc: true
    html-math-method: katex
    css: style.css
---

```{r}
#| echo: false

library(fontawesome)
```

## Before the Program

- **Sign up for GitHub** [`r fontawesome::fa(name = "link")`](https://github.com) Sign up for a free GitHub account if you don't already have one. Make sure to pick a username that you feel comfortable sharing on your CV. You will most likely use your GitHub username for many years in your data science career. Fill out [this survey](https://forms.gle/CTJkSfg1J2Y8Jbr16) to let us know what your username is. Many of you have already done this.

- **Install R** [`r fontawesome::fa(name = "link")`](https://mirror.las.iastate.edu/CRAN/) Yes, you do need to download and install R even if you have downloaded before. There is a newer version.

- **Install RStudio** [`r fontawesome::fa(name = "link")`](https://posit.co/download/rstudio-desktop/) Yes, you do need to download and install RStudio even if you have downloaded before. There is a newer version. Download the free Desktop version.

- **Install and setup git** [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=7926437&node=33713927&a=41919805&autoplay=1) [`r fontawesome::fa(name = "chalkboard-teacher")`](https://socaldatascience.github.io/bootcamp-materials-2023/slides/day00-prep/00a-git-github-install.html)

- **Test your installations**  [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=7926702&node=33717865&a=36939698&autoplay=1) 


## Week 1

## Week 2

## Week 3

## Week 5

## Week 6